### ISSUE TITLE
Author archive when byline with mapped author has different slug than the author

### ISSUE THREAD

**Issue by lakrisgubben** [danielbachhuber/bylines#101]
If you have a user "Jane Doe", with the user_nicename janedoe and you then create a byline mapped to that user with the name "Jane Doe" that byline will probably (i.e. if you don't choose another slug) get the slug jane-doe. This leads to two different author archives being available: the byline (which probably is the intended archive) at mysite.com/author/jane-doe/ and the author (probably, but maybe not, unintended) at mysite.com/author/janedoe. The first archive will only contain posts assigned to that byline while the last one can contain posts from totally different bylines just because the user was the one publishing the post.

I'm not sure if this is a problem that should be tackled by this plugin, and if so, how. :) But I thought it would be interesting to discuss it. One way to handle this would be to hook into something like template_redirect and check if we're on an author archive, and if a byline doesn't exist with this slug, check if the author has a mapped byline and then redirect to that byline. Problem with this might be an expensive query to check the term_meta table for user_login. Another option would be to force a mapped byline to have the same slug as the user_nicename, but I can see that maybe that's not something that would be desirable... What are your thoughts on this Daniel?

**Comment by danielbachhuber** [comment]
The expected behavior is similar to:

> One way to handle this would be to hook into something like template_redirect and check if we're on an author archive, and if a byline doesn't exist with this slug, check if the author has a mapped byline and then redirect to that byline. 

Co-Authors Plus already does this, so I think it's a safe assumption to take in Bylines too.

**Comment by lakrisgubben** [comment]
Cool, I'll look at how Co-Authors Plus does this and try to make a PR if you'd like.

Do you think the best place to have this functionality is in `class Query`?

**Comment by danielbachhuber** [comment]
> Do you think the best place to have this functionality is in `class Query`?

Good question. I think `class Content_Model` might be more appropriate, as it has `filter_term_link` and some other "default byline behavior" type logic.

It'd be great to have tests on this too.

**Comment by lakrisgubben** [comment]
I'm not totally sure how to write the tests checking that the redirect will take place since (as far as I can tell) you cannot do a redirect in a test because of headers already sent. I couldn't find any tests in co-authors plus either to get inspiration from. But seeing as my knowledge about WP unit tests isn't that deep maybe you've got some better ideas about this than me? :)

**Comment by danielbachhuber** [comment]
> I'm not totally sure how to write the tests checking that the redirect will take place since (as far as I can tell) you cannot do a redirect in a test because of headers already sent

If you're calling `wp_safe_redirect()`, then you can prevent the actual redirect from occurring.

> I couldn't find any tests in co-authors plus either to get inspiration from.

Co-Authors Plus is lacking many tests :)

> But seeing as my knowledge about WP unit tests isn't that deep maybe you've got some better ideas about this than me? :)

I'd suggest adding the following filter in `setUp()` (and removing in `tearDown()`):

```
add_filter( 'wp_redirect', array( $this, 'filter_wp_redirect' ), 10, 2 );

/**
 * Capture any redirects
 */
public function filter_wp_redirect( $location, $status ) {

	$this->final_redirect_location = $location;
	$this->go_to( $location );

	// Prevent the redirect from happening
	return false;
}
```

You can then `$this->assertEquals()` on `$this->final_redirect_location` in your test.

**Comment by lakrisgubben** [comment]
Thanks for the pointers @danielbachhuber :)

I've done a first pass at this (PR) added, not sure if the test is in the correct file or if you'd like a new file `test-bylines-rewrite.php` just let me know.

**Comment by danielbachhuber** [comment]
🔨
