### ISSUE TITLE
Can't remove last Byline

### ISSUE THREAD

**Issue by superbia** [danielbachhuber/bylines#98]
The last Byline can't be removed from a post. When you remove the last Byline, the bylines form field is also removed. This means that the `action_save_post_bylines_metabox` method returns before the `set_post_bylines` method can run. Not sure if this is by design or if it's a bug. There are instances where we wouldn't want to assign a Byline to a post.

**Comment by danielbachhuber** [comment]
Thanks for the bug report. I'm pretty sure this is a bug — I'll take a look.
